package com.github.se.gatherspot.firebase

enum class FirebaseCollection {
  PROFILES,
  EVENTS,
  CHATS,
  REGISTERED_EVENTS,
  REGISTERED_USERS,
  FRIENDS,
  FOLLOWING,
  FOLLOWERS,
  REQUESTED_FRIENDS,
  PENDING_FRIENDS,
  EVENT_RATINGS,
  ORGANIZER_RATINGS,
}
